# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "lightmix_wav-0.5.0-IIrulooTVQD9sWDdiGai2Ix5sP7uzZ8YrBY1oGt0BhKz";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix_wav/archive/refs/tags/0.5.0.tar.gz";
      hash = "sha256-QYreiBlcMnKuYbiyWqgThVsXJ0Xs3dQMwvMcJ7A66o8=";
    };
  }
]
